// This file is automatically generated. Do not modify it manually.
// This is the Firebase configuration for your web app.
// For more information, see the Firebase documentation:
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
export const firebaseConfig = {
  projectId: "studio-227719239-efe98",
  appId: "1:630277961426:web:bb3c1083c72518abf4df0b",
  apiKey: "AIzaSyAmsBIjLGpCofUcV5M5aIiWBMqrqu6w2rg",
  authDomain: "studio-227719239-efe98.firebaseapp.com",
  measurementId: "",
  messagingSenderId: "630277961426"
};
